# Development Namespace LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: expenseflow-dev
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 2
        memory: 2Gi
      min:
        cpu: 10m
        memory: 32Mi
---
# Staging Namespace LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: expenseflow-staging
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 2
        memory: 1Gi
      min:
        cpu: 10m
        memory: 32Mi
