# Development Namespace Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: expenseflow-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    configmaps: "15"
    secrets: "15"
---
# Staging Namespace Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: expenseflow-staging
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "30"
    services: "15"
    persistentvolumeclaims: "10"
