openapi: 3.0.3
info:
  title: ExpenseFlow Analytics Categories API
  description: Endpoint for retrieving expense category breakdown
  version: 1.0.0

paths:
  /api/analytics/categories:
    get:
      summary: Get category breakdown
      description: Returns expense breakdown by category for a given period
      operationId: getAnalyticsCategories
      tags:
        - Analytics
      security:
        - bearerAuth: []
      parameters:
        - name: period
          in: query
          description: Period in YYYY-MM format (default current month)
          required: false
          schema:
            type: string
            pattern: '^\d{4}-(0[1-9]|1[0-2])$'
            example: "2025-12"
      responses:
        '200':
          description: Category spending breakdown
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryBreakdownDto'
              example:
                period: "2025-12"
                totalSpending: 2450.75
                transactionCount: 45
                categories:
                  - category: "Food & Dining"
                    amount: 850.25
                    percentage: 34.7
                    transactionCount: 18
                  - category: "Transportation"
                    amount: 425.00
                    percentage: 17.3
                    transactionCount: 8
                  - category: "Shopping"
                    amount: 675.50
                    percentage: 27.6
                    transactionCount: 12
                  - category: "Uncategorized"
                    amount: 500.00
                    percentage: 20.4
                    transactionCount: 7
        '400':
          description: Invalid period format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                title: "Validation Error"
                detail: "Invalid period format. Expected YYYY-MM (e.g., 2025-12)."
                status: 400
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Azure AD access token

  schemas:
    CategoryBreakdownDto:
      type: object
      required:
        - period
        - totalSpending
        - transactionCount
        - categories
      properties:
        period:
          type: string
          pattern: '^\d{4}-(0[1-9]|1[0-2])$'
          description: Period in YYYY-MM format
          example: "2025-12"
        totalSpending:
          type: number
          format: decimal
          minimum: 0
          description: Total spending for the period
          example: 2450.75
        transactionCount:
          type: integer
          minimum: 0
          description: Total transactions in the period
          example: 45
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategorySpendingDto'
          description: Breakdown by category

    CategorySpendingDto:
      type: object
      required:
        - category
        - amount
        - percentage
        - transactionCount
      properties:
        category:
          type: string
          description: Category name
          example: "Food & Dining"
        amount:
          type: number
          format: decimal
          minimum: 0
          description: Total amount in this category
          example: 850.25
        percentage:
          type: number
          format: decimal
          minimum: 0
          maximum: 100
          description: Percentage of total spending
          example: 34.7
        transactionCount:
          type: integer
          minimum: 0
          description: Number of transactions
          example: 18

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
