# OpenAPI Contract: Receipt Thumbnail Endpoints
# Feature: 030-receipt-thumbnails
# Date: 2026-01-08

openapi: 3.0.3
info:
  title: ExpenseFlow Receipt Thumbnail API
  description: Endpoints for managing receipt thumbnail generation
  version: 1.0.0

paths:
  /api/receipts/{id}/regenerate-thumbnail:
    post:
      summary: Regenerate thumbnail for a receipt
      description: |
        Triggers regeneration of the thumbnail for a specific receipt.
        Useful when the original thumbnail failed or needs updating.
      operationId: regenerateThumbnail
      tags:
        - Receipts
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Receipt ID
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Thumbnail regeneration queued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThumbnailRegenerationResponse'
        '404':
          description: Receipt not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user does not own this receipt

  /api/admin/thumbnails/backfill:
    post:
      summary: Start thumbnail backfill job
      description: |
        Initiates a background job to generate thumbnails for all receipts
        that are missing them. Admin-only endpoint.
      operationId: startThumbnailBackfill
      tags:
        - Admin
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThumbnailBackfillRequest'
      responses:
        '202':
          description: Backfill job started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThumbnailBackfillResponse'
        '409':
          description: Backfill job already running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - admin access required

  /api/admin/thumbnails/backfill/status:
    get:
      summary: Get thumbnail backfill status
      description: |
        Returns the current status of the thumbnail backfill job,
        including progress counts and any errors.
      operationId: getThumbnailBackfillStatus
      tags:
        - Admin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Backfill status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThumbnailBackfillStatus'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - admin access required

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ThumbnailRegenerationResponse:
      type: object
      properties:
        receiptId:
          type: string
          format: uuid
          description: ID of the receipt being processed
        jobId:
          type: string
          description: Hangfire job ID for tracking
        message:
          type: string
          example: "Thumbnail regeneration queued"
      required:
        - receiptId
        - jobId
        - message

    ThumbnailBackfillRequest:
      type: object
      properties:
        batchSize:
          type: integer
          minimum: 1
          maximum: 500
          default: 50
          description: Number of receipts to process per batch
        contentTypes:
          type: array
          items:
            type: string
          description: |
            Optional filter for content types to process.
            If omitted, all supported types are processed.
          example: ["application/pdf", "text/html"]

    ThumbnailBackfillResponse:
      type: object
      properties:
        jobId:
          type: string
          description: Hangfire job ID for tracking
        estimatedCount:
          type: integer
          description: Estimated number of receipts to process
        message:
          type: string
          example: "Backfill job started"
      required:
        - jobId
        - message

    ThumbnailBackfillStatus:
      type: object
      properties:
        status:
          type: string
          enum: [idle, running, completed, failed]
          description: Current job status
        jobId:
          type: string
          nullable: true
          description: Current or last job ID
        processedCount:
          type: integer
          description: Number of receipts processed
        failedCount:
          type: integer
          description: Number of thumbnails that failed to generate
        totalCount:
          type: integer
          description: Total receipts without thumbnails at job start
        startedAt:
          type: string
          format: date-time
          nullable: true
        completedAt:
          type: string
          format: date-time
          nullable: true
        currentBatch:
          type: integer
          description: Current batch number being processed
        errors:
          type: array
          items:
            type: object
            properties:
              receiptId:
                type: string
                format: uuid
              error:
                type: string
          maxItems: 100
          description: Recent errors (limited to last 100)
      required:
        - status
        - processedCount
        - failedCount

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
