/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedStatementsIndexRouteImport } from './routes/_authenticated/statements/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated/receipts/index'
import { Route as AuthenticatedMissingReceiptsIndexRouteImport } from './routes/_authenticated/missing-receipts/index'
import { Route as AuthenticatedMatchingIndexRouteImport } from './routes/_authenticated/matching/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedTransactionsTransactionIdRouteImport } from './routes/_authenticated/transactions/$transactionId'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports/$reportId'
import { Route as AuthenticatedReceiptsReceiptIdRouteImport } from './routes/_authenticated/receipts/$receiptId'
import { Route as AuthenticatedPredictionsPatternsRouteImport } from './routes/_authenticated/predictions/patterns'
import { Route as AuthenticatedAdminExtractionCorrectionsRouteImport } from './routes/_authenticated/admin/extraction-corrections'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStatementsIndexRoute =
  AuthenticatedStatementsIndexRouteImport.update({
    id: '/statements/',
    path: '/statements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissingReceiptsIndexRoute =
  AuthenticatedMissingReceiptsIndexRouteImport.update({
    id: '/missing-receipts/',
    path: '/missing-receipts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatchingIndexRoute =
  AuthenticatedMatchingIndexRouteImport.update({
    id: '/matching/',
    path: '/matching/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsTransactionIdRoute =
  AuthenticatedTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsReceiptIdRoute =
  AuthenticatedReceiptsReceiptIdRouteImport.update({
    id: '/receipts/$receiptId',
    path: '/receipts/$receiptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPredictionsPatternsRoute =
  AuthenticatedPredictionsPatternsRouteImport.update({
    id: '/predictions/patterns',
    path: '/predictions/patterns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExtractionCorrectionsRoute =
  AuthenticatedAdminExtractionCorrectionsRouteImport.update({
    id: '/admin/extraction-corrections',
    path: '/admin/extraction-corrections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/extraction-corrections': typeof AuthenticatedAdminExtractionCorrectionsRoute
  '/predictions/patterns': typeof AuthenticatedPredictionsPatternsRoute
  '/receipts/$receiptId': typeof AuthenticatedReceiptsReceiptIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/matching': typeof AuthenticatedMatchingIndexRoute
  '/missing-receipts': typeof AuthenticatedMissingReceiptsIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statements': typeof AuthenticatedStatementsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/extraction-corrections': typeof AuthenticatedAdminExtractionCorrectionsRoute
  '/predictions/patterns': typeof AuthenticatedPredictionsPatternsRoute
  '/receipts/$receiptId': typeof AuthenticatedReceiptsReceiptIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/matching': typeof AuthenticatedMatchingIndexRoute
  '/missing-receipts': typeof AuthenticatedMissingReceiptsIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statements': typeof AuthenticatedStatementsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/extraction-corrections': typeof AuthenticatedAdminExtractionCorrectionsRoute
  '/_authenticated/predictions/patterns': typeof AuthenticatedPredictionsPatternsRoute
  '/_authenticated/receipts/$receiptId': typeof AuthenticatedReceiptsReceiptIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/matching/': typeof AuthenticatedMatchingIndexRoute
  '/_authenticated/missing-receipts/': typeof AuthenticatedMissingReceiptsIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/statements/': typeof AuthenticatedStatementsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/extraction-corrections'
    | '/predictions/patterns'
    | '/receipts/$receiptId'
    | '/reports/$reportId'
    | '/transactions/$transactionId'
    | '/analytics'
    | '/matching'
    | '/missing-receipts'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/admin/extraction-corrections'
    | '/predictions/patterns'
    | '/receipts/$receiptId'
    | '/reports/$reportId'
    | '/transactions/$transactionId'
    | '/analytics'
    | '/matching'
    | '/missing-receipts'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/statements'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/extraction-corrections'
    | '/_authenticated/predictions/patterns'
    | '/_authenticated/receipts/$receiptId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/transactions/$transactionId'
    | '/_authenticated/analytics/'
    | '/_authenticated/matching/'
    | '/_authenticated/missing-receipts/'
    | '/_authenticated/receipts/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/statements/'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statements/': {
      id: '/_authenticated/statements/'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missing-receipts/': {
      id: '/_authenticated/missing-receipts/'
      path: '/missing-receipts'
      fullPath: '/missing-receipts'
      preLoaderRoute: typeof AuthenticatedMissingReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matching/': {
      id: '/_authenticated/matching/'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AuthenticatedMatchingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/$transactionId': {
      id: '/_authenticated/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthenticatedTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts/$receiptId': {
      id: '/_authenticated/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof AuthenticatedReceiptsReceiptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictions/patterns': {
      id: '/_authenticated/predictions/patterns'
      path: '/predictions/patterns'
      fullPath: '/predictions/patterns'
      preLoaderRoute: typeof AuthenticatedPredictionsPatternsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/extraction-corrections': {
      id: '/_authenticated/admin/extraction-corrections'
      path: '/admin/extraction-corrections'
      fullPath: '/admin/extraction-corrections'
      preLoaderRoute: typeof AuthenticatedAdminExtractionCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminExtractionCorrectionsRoute: typeof AuthenticatedAdminExtractionCorrectionsRoute
  AuthenticatedPredictionsPatternsRoute: typeof AuthenticatedPredictionsPatternsRoute
  AuthenticatedReceiptsReceiptIdRoute: typeof AuthenticatedReceiptsReceiptIdRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedTransactionsTransactionIdRoute: typeof AuthenticatedTransactionsTransactionIdRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedMatchingIndexRoute: typeof AuthenticatedMatchingIndexRoute
  AuthenticatedMissingReceiptsIndexRoute: typeof AuthenticatedMissingReceiptsIndexRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStatementsIndexRoute: typeof AuthenticatedStatementsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminExtractionCorrectionsRoute:
    AuthenticatedAdminExtractionCorrectionsRoute,
  AuthenticatedPredictionsPatternsRoute: AuthenticatedPredictionsPatternsRoute,
  AuthenticatedReceiptsReceiptIdRoute: AuthenticatedReceiptsReceiptIdRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedTransactionsTransactionIdRoute:
    AuthenticatedTransactionsTransactionIdRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedMatchingIndexRoute: AuthenticatedMatchingIndexRoute,
  AuthenticatedMissingReceiptsIndexRoute:
    AuthenticatedMissingReceiptsIndexRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStatementsIndexRoute: AuthenticatedStatementsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
